### ISSUE TITLE
按钮权限有吗？

### ISSUE THREAD

**Issue by Gooooodman** [pl1998/vue_system#5]
## Question（提问）

页面中的 按钮权限有吗？

比如 权限中 增加权限的 按钮 
 <el-button type="success" icon="el-icon-plus" @click="add" />

**Comment by pl1998** [comment]
https://github.com/pl1998/vue_admin/issues/4 可以看看这个。所有的权限登录后会存在store里面，提供了权限控制方法进行按钮展示
